name: gstest
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ncurses
  - libuuid
  - xz
  - zstd
  - xorg-libxau
  - pthread-stubs
  - ld_impl_linux-64
  - xorg-libx11
  - openssl
  - readline
  - _openmp_mutex
  - libmpdec
  - pip
  - libxcb
  - xorg-xorgproto
  - bzip2
  - libffi
  - expat
  - libzlib
  - tk
  - python_abi
  - lz4-c
  - python
  - xorg-libxdmcp
  - ca-certificates
  - zlib
  - sqlite
  - bioconda::mafft
  - conda-forge::openpyxl
