name: GeneScanner-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - expat
  - ld_impl_linux-64
  - libffi
  - libmpdec
  - libuuid
  - libxcb
  - libzlib
  - lz4-c
  - ncurses
  - openssl
  - pip
  - pthread-stubs
  - python
  - python_abi
  - readline
  - sqlite
  - tk
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xorgproto
  - xz
  - zlib
  - zstd
  - pip:
      - biopython
      - contourpy
      - cycler
      - fonttools
      - kiwisolver
      - matplotlib
      - numpy
      - packaging
      - pandas
      - pillow
      - pyparsing
      - python-dateutil
      - pytz
      - seaborn
      - six
      - tzdata
      - xlsxwriter
